database01:
  -
    dbms: "mysql"
    user: "root"
    password: "db01"
    protocol: "tcp(127.0.0.1:3306)"
    dbname: "mysql"
database02:
  -
    dbms: "mysql"
    user: "root"
    password: "db02"
    protocol: "tcp(127.0.0.1:3307)"
    dbname: "mysql"